### ISSUE TITLE
Suggestion: Change Title Color

### ISSUE THREAD

**Issue by Chrisnwachukwu107** [ProgrammerChris6002/github-crash-course#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
    color: #efa82f;
}
```
